-- MySQL Script generated by MySQL Workbench
-- Mon Jun 28 15:43:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fiverr
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fiverr` ;

-- -----------------------------------------------------
-- Schema fiverr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiverr` DEFAULT CHARACTER SET utf8 ;
USE `fiverr` ;

-- -----------------------------------------------------
-- Table `fiverr`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) BINARY NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `startdate` VARCHAR(255) NOT NULL,
  `duration` INT NOT NULL,
  `payement` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`candidate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intro` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`team_has_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`team_has_job` (
  `team_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  PRIMARY KEY (`team_id`, `job_id`),
  INDEX `fk_team_has_job_job1_idx` (`job_id` ASC) VISIBLE,
  INDEX `fk_team_has_job_team_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_job_team`
    FOREIGN KEY (`team_id`)
    REFERENCES `fiverr`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_job_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `fiverr`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`team_has_job_has_candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`team_has_job_has_candidate` (
  `team_has_job_team_id` INT NOT NULL,
  `team_has_job_job_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`team_has_job_team_id`, `team_has_job_job_id`, `candidate_id`),
  INDEX `fk_team_has_job_has_candidate_candidate1_idx` (`candidate_id` ASC) VISIBLE,
  INDEX `fk_team_has_job_has_candidate_team_has_job1_idx` (`team_has_job_team_id` ASC, `team_has_job_job_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_job_has_candidate_team_has_job1`
    FOREIGN KEY (`team_has_job_team_id` , `team_has_job_job_id`)
    REFERENCES `fiverr`.`team_has_job` (`team_id` , `job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_job_has_candidate_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `fiverr`.`candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`user_has_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`user_has_team` (
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `team_id`),
  INDEX `fk_user_has_team_team1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_user_has_team_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_team_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fiverr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_team_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `fiverr`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiverr`.`user_has_candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiverr`.`user_has_candidate` (
  `user_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `candidate_id`),
  INDEX `fk_user_has_candidate_candidate1_idx` (`candidate_id` ASC) VISIBLE,
  INDEX `fk_user_has_candidate_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_candidate_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fiverr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_candidate_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `fiverr`.`candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
